spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/payment-form-db
spring.datasource.username=postgres
spring.datasource.password=erman2023

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

token.signing.key=AAAAYgAAAGEAAAB1AAAAeQAAAHIAAAB6AAAAaAAAAGEAAABuAAAAMQAAADIAAAAz
